# Generated by Django 4.0.6 on 2022-07-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialPart', '0002_enemy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enemy',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
